version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.alpine
    command: sh -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/sandbox-rails
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes_from:
      - app:ro
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    image: postgres:14.0
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pg_data:
    driver: local
