version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/sandbox-rails
      - tmp_data:/sandbox-rails/tmp
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - tmp_data:/sandbox-rails/tmp
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    image: postgres:14.0
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pg_data:
    driver: local
  tmp_data: