default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sandbox_rails_development

test:
  <<: *default
  database: sandbox_rails_test

production:
  <<: *default
  database: sandbox_rails_production
  username: sandbox_rails
  password: <%= ENV['SANDBOX_RAILS_DATABASE_PASSWORD'] %>
