default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sandbox_rails_development

test:
  <<: *default
  database: sandbox_rails_test

production:
  <<: *default
  database: sandbox_rails_production
  username: sandbox_rails
  password: <%= ENV['SANDBOX_RAILS_DATABASE_PASSWORD'] %>
