name: GCP Demo

on:
  push:
    # tags:
    #   - v**

jobs:
  Explore-GitHub-Actions:
    # if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: projects/1079700346748/locations/global/workloadIdentityPools/jinugasachio/providers/github-actions
          service_account: github-actions-oidc@jinugasachio.iam.gserviceaccount.com

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/jinugasachio/nginx
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      