name: GCP Demo

on:
  push:
    tags:
      - v**
jobs:
  Explore-GitHub-Actions:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
